name: 'SSM output to S3'
description: 'Sync SSM output to S3 bucket'
inputs:
  ssm-path:  # id of input
    description: 'The SSM path'
    required: true
  s3-bucket:
    description: 'The name of the bucket'
    required: true
  s3-file:
    description: 'The full path to the file in the bucket'
    required: true
  ssm-additional-paths:  # id of input
    description: 'Additional SSM paths, split with comma'
    required: false
outputs:
  s3ObjectUrl: # id of output
    description: 'The full path of the file in the bucket'
runs:
  using: 'node16'
  main: 'index.js'